name: aic
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - freesimplegui
      - imbalanced-learn
      - lightgbm
      - numpy
      - openml
      - pandas
      - pmlb
      - pymfe
      - scikit-learn
      - scipy
      - setuptools
      - tpot
      - xgboost
